# Extension id: anweber.vscode-httpyac
@host = http://localhost:3000/

###
POST {{host}}login
Content-Type: application/json
{
    "username": "llius123",
    "password": "1234"
}


POST {{host}}register
Content-Type: application/json
{
    "username": "qwe",
    "password": "1234",
    "password_repeated": "1234",
    "email": "email@email.com"
}